name: ATV Avrupa M3U8 Güncelle

on:
  workflow_dispatch:

  schedule:
    - cron: "*/10 * * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu indir
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Gerekli paketleri kur
        run: |
          python -m pip install --upgrade pip
          pip install streamlink

      - name: M3U8 bağlantısını güncelle
        run: python atvavrupa.py

      - name: Değişiklikleri GitHub'a gönder
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add streams/atvavrupa.m3u8

          if git diff --cached --quiet; then
            echo "Değişiklik yok."
          else
            git commit -m "ATV Avrupa M3U8 güncellendi"
            git pull --rebase origin main
            git push origin main
          fi
