name: atvavrupa update

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: atvavrupa-update
  cancel-in-progress: false

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Repository'yi indir
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Gerekli paketleri kur
        run: |
          python -m pip install --upgrade pip
          pip install requests streamlink

      - name: Python dosyasını çalıştır
        run: |
          python atvavrupa.py

      - name: Streams klasörünü Git'e ekle
        run: |
          git add streams/

      - name: Değişiklikleri kontrol et ve gönder
        run: |
          if git diff --cached --quiet; then
            echo "Değişiklik bulunamadı."
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

            git commit -m "atvavrupa updated"

            git pull --rebase origin main
            git push origin HEAD:main
          fi
