name: ATV Avrupa M3U8

on:
  schedule:
    - cron: "16 */2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Repository indir
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Requests yükle
        run: pip install requests

      - name: ATV Avrupa M3U8 al
        run: |
          python res/26-2/avrupa.py > res/26-2/avrupa.m3u8

      - name: Değişiklikleri kontrol et
        id: git_check
        run: |
          git add res/26-2/avrupa.m3u8

          if git diff --cached --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: GitHub'a kaydet
        if: steps.git_check.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git commit -m "ATV Avrupa M3U8 güncellendi"
          git push
