name: ShowMax M3U8 Güncelle

on:
  workflow_dispatch:

  schedule:
    - cron: "16 */2 * * *"

permissions:
  contents: write

jobs:
  update-showmax:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu indir
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Requests yükle
        run: pip install requests

      - name: ShowMax bağlantısını al
        run: |
          python res/26-2/shmax.py > res/26-2/shmax.m3u8

      - name: Dosyayı GitHub'a kaydet
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add res/26-2/shmax.m3u8

          if git diff --cached --quiet; then
            echo "Değişiklik bulunamadı."
          else
            git commit -m "ShowMax M3U8 güncellendi"
            git push origin HEAD:main
          fi
